### ISSUE TITLE
Notebook on binder not editable

### ISSUE THREAD

**Issue by jbrea** [JuliaPluto/PlutoSliderServer.jl#52]
When I want to run e.g. [this notebook](https://bio322.epfl.ch/notebooks/model_evaluation.html) on binder (clicking the "run on binder" button in the notebook), it loads fine on binder, but I cannot edit the notebook, unless I navigate to the Pluto main page (by clicking on the Pluto logo at the top), shut down the notebook (clicking the "x" button) and restart it again (clicking on the file name). What does go wrong here? Note that I am using the custom binder url `Export_binder_url = "https://mybinder.org/v2/gh/jbrea/MLCourse/binder"`. Opening the notebook directly on binder through [this link](https://mybinder.org/v2/gh/jbrea/MLCourse/binder?urlpath=pluto/open?path%3D/home/jovyan/MLCourse/notebooks/model_evaluation.jl) works fine.

**Comment by fonsp** [comment]
There is probably an error in the JS console in the chrome devtools.

Not sure if this caused the issue, but you should version-pin the binder URL, because the pluto version used in binder needs to exactly match the version used to generate the HTML. *(You can also leave it empty to use our shared binder versions, which is always version-matched automatically.)*

**Comment by jbrea** [comment]
Thanks for the feedback.

I do indeed get an error message in the console, but I have difficulties interpreting it.

![js_console_error](https://user-images.githubusercontent.com/12857162/153713238-7c9ca5cc-4502-4ae5-96ec-e9a6f60a9399.png)

I don't think the version is a problem. I use a custom docker image on binder that uses  the same manifest file as the one that is used by the sliderserver.

I also tried `Export_binder_url = "https://mybinder.org/v2/gh/jbrea/MLCourse/binder?urlpath=pluto/open?path%3D/home/jovyan/MLCourse/notebooks/"` but it looks like the string after the question mark is ignored.

**Comment by fonsp** [comment]
Thanks so much for this report @jbrea ! 

This turned out to be a bug in Pluto's frontend, probably caused by my recent rewrite of the binder backend (https://github.com/fonsp/Pluto.jl/pull/2029). The problem occurred when both a sliderserver URL and a binder URL were set, I forgot to test this combination...

Fix is here: https://github.com/fonsp/Pluto.jl/pull/2043 . I tested this on your combination of statefile, notebook, sliderserver and binder URL and it works!


<img width="567" alt="Schermafbeelding 2022-04-20 om 23 06 20" src="https://user-images.githubusercontent.com/6933510/164322973-0a9f63fe-ff77-4731-b4b8-309ef0de949a.png">

**Comment by fonsp** [comment]
You should restore the setting 
```
Export_binder_url = "https://mybinder.org/v2/gh/jbrea/MLCourse/binder?urlpath=pluto/open?path%3D/home/jovyan/MLCourse/notebooks/"
``` 
to the original: 
```
Export_binder_url = "https://mybinder.org/v2/gh/jbrea/MLCourse/binder"
```

This URL should point to the root, e.g. 
```
"https://mybinder.org/v2/gh/fonsp/pluto-on-binder/v0.19.0"
```
and our client will use this as starting point for binder's REST API, e.g. by adding `?urlpath=pluto/...`.

**Comment by fonsp** [comment]
I also recommend setting `Export_baked_statefile = false`, this will slightly improve loading times and show a loading bar.

**Comment by fonsp** [comment]
Also some extra context: The two 404 errors in your screenshot are "expected", they both have fallbacks. 

You can ignore the `binder_token_please` request, this is just a bonus feature if it works.

The `/open?path=...` request might be interesting to understand. Here is how we connect to binder in the background, then start running the notebook on that server, then connect to the running notebook: 

https://github.com/fonsp/Pluto.jl/blob/v0.19.0/frontend/common/Binder.js

In particular, this is where we make HTTP requests to Pluto's server to launch the notebook: https://github.com/fonsp/Pluto.jl/blob/90d71f86c013281a51fb642ae82403a3d3231a91/frontend/common/Binder.js#L128-L142 We first try to open a notebook file with the same name on the binder server (e.g. `model_evaluation.jl`), and if that doesn't work, we ask the server to download the notebook file using its full URL (e.g. `https://bio322.epfl.ch/notebooks/model_evaluation.jl`).

This first method, using the notebook filename, almost never works, because most people use https://github.com/fonsp/pluto-on-binder/ (which does not have your notebooks locally), and because the path is dropped, only the filename is used. This is old code that could definitely be improved!
